# Generated by Django 2.0.5 on 2019-05-18 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('position', models.CharField(max_length=50, verbose_name='职位')),
                ('profile', models.TextField(default='', verbose_name='基本信息')),
                ('contact', models.TextField(default='', verbose_name='联系方式')),
                ('stack', models.TextField(default='', verbose_name='技术栈')),
                ('eduction', models.TextField(default='', verbose_name='教育信息')),
                ('work', models.TextField(default='', verbose_name='工作经历')),
                ('project', models.TextField(default='', verbose_name='个人项目')),
                ('trophy', models.TextField(default='', verbose_name='奖项与证书')),
                ('aboutme', models.TextField(default='', verbose_name='自我评价')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '简历信息',
                'verbose_name_plural': '简历信息',
            },
        ),
    ]
