# Generated by Django 2.0.5 on 2019-05-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='eduction',
            new_name='education',
        ),
    ]
